// services/moon/src/components/raven/RavenLibraryCard.vue
<script setup>
import {computed} from 'vue';

const props = defineProps({
  item: {
    type: Object,
    required: true,
  },
  status: {
    type: Object,
    default: null,
  },
});

const hasCover = computed(() => Boolean(props.item?.coverImage));

const statusState = computed(() => props.status?.state ?? null);

const isInProgress = computed(() => {
  const state = statusState.value;
  return state === 'pending' || state === 'downloading' || state === 'queued';
});

const isFailed = computed(() => statusState.value === 'failed');

const isCompleted = computed(() => statusState.value === 'completed');

const progressValue = computed(() => {
  const value = props.status?.progress;
  return typeof value === 'number' ? Math.min(100, Math.max(0, value)) : null;
});

const statusMessage = computed(() => {
  if (!props.status) return '';
  if (props.status.message) return props.status.message;
  if (isCompleted.value) return 'Download completed';
  if (isFailed.value) return 'Download failed';
  if (isInProgress.value) return 'Downloading';
  if (statusState.value === 'queued') return 'Queued';
  return '';
});

const subtitle = computed(() => props.item?.subtitle ?? props.item?.author ?? props.item?.series);
</script>

<template>
  <v-card data-test="raven-library-card" class="h-100 d-flex flex-column" elevation="6">
    <v-img
        v-if="hasCover"
        :src="item.coverImage"
        height="160"
        cover
        class="rounded-t"
    />
    <v-card-title class="text-h6">{{ item.title ?? 'Untitled series' }}</v-card-title>
    <v-card-subtitle v-if="subtitle">{{ subtitle }}</v-card-subtitle>
    <v-card-text class="flex-grow-1">
      <p v-if="item.description" class="mb-4 text-body-2">{{ item.description }}</p>
      <div v-if="statusState" class="mb-2">
        <v-chip
            v-if="isCompleted"
            color="success"
            size="small"
            variant="tonal"
            class="mr-2"
        >
          Ready
        </v-chip>
        <v-chip
            v-else-if="isFailed"
            color="error"
            size="small"
            variant="tonal"
            class="mr-2"
        >
          Failed
        </v-chip>
        <v-chip
            v-else
            color="primary"
            size="small"
            variant="tonal"
            class="mr-2"
        >
          {{ isInProgress ? 'Downloading' : statusState }}
        </v-chip>
      </div>
      <v-progress-linear
          v-if="progressValue !== null"
          :model-value="progressValue"
          height="6"
          color="primary"
          rounded
          data-test="download-progress"
      />
      <div
          v-if="statusMessage"
          class="mt-2 text-body-2"
          :class="{'text-error': isFailed}"
      >
        {{ statusMessage }}
      </div>
    </v-card-text>
    <v-divider v-if="item.downloadedAt" />
    <v-card-text v-if="item.downloadedAt" class="text-caption text-medium-emphasis">
      Downloaded {{ new Date(item.downloadedAt).toLocaleString?.() ?? item.downloadedAt }}
    </v-card-text>
  </v-card>
</template>

// services/moon/src/components/raven/RavenLibraryCard.jsx
import React, { useMemo } from 'react';
import {
  Badge,
  Box,
  Card,
  CardBody,
  CardFooter,
  CardHeader,
  Progress,
  Stack,
  Text,
} from '@chakra-ui/react';

function normalizeProgress(value) {
  if (typeof value !== 'number' || Number.isNaN(value)) {
    return null;
  }
  return Math.max(0, Math.min(100, value));
}

function formatDownloadDate(value) {
  if (!value) {
    return null;
  }
  try {
    const date = new Date(value);
    if (!Number.isNaN(date.getTime())) {
      return date.toLocaleString();
    }
  } catch (error) {
    // Ignore invalid dates
  }
  return value;
}

export default function RavenLibraryCard({ item, status }) {
  const hasCover = Boolean(item?.coverImage);
  const statusState = status?.state ?? null;

  const isInProgress = useMemo(() => {
    if (!statusState) {
      return false;
    }
    return ['pending', 'downloading', 'queued'].includes(statusState);
  }, [statusState]);

  const isFailed = statusState === 'failed';
  const isCompleted = statusState === 'completed';

  const progressValue = normalizeProgress(status?.progress);

  const statusMessage = useMemo(() => {
    if (!status) {
      return '';
    }
    if (status.message) {
      return status.message;
    }
    if (isCompleted) {
      return 'Download completed';
    }
    if (isFailed) {
      return 'Download failed';
    }
    if (statusState === 'queued') {
      return 'Queued';
    }
    if (isInProgress) {
      return 'Downloading';
    }
    return '';
  }, [isCompleted, isFailed, isInProgress, status, statusState]);

  const subtitle = item?.subtitle ?? item?.author ?? item?.series ?? '';
  const downloadedAtLabel = formatDownloadDate(item?.downloadedAt);

  const statusColor = isCompleted ? 'green' : isFailed ? 'red' : 'purple';
  const statusLabel = isCompleted
    ? 'Ready'
    : isFailed
    ? 'Failed'
    : isInProgress
    ? 'Downloading'
    : statusState ?? 'Pending';

  return (
    <Card data-testid="raven-library-card" height="100%" variant="outline">
      {hasCover && (
        <Box
          as="img"
          src={item.coverImage}
          alt={item.title ?? 'Series cover'}
          height="160px"
          objectFit="cover"
          borderTopLeftRadius="md"
          borderTopRightRadius="md"
        />
      )}
      <CardHeader pb={0}>
        <Stack spacing={1}>
          <Text fontWeight="bold" fontSize="lg">
            {item?.title ?? 'Untitled series'}
          </Text>
          {subtitle ? (
            <Text fontSize="sm" color="gray.500">
              {subtitle}
            </Text>
          ) : null}
        </Stack>
      </CardHeader>
      <CardBody>
        <Stack spacing={3}>
          {item?.description ? (
            <Text fontSize="sm" color="gray.600" _dark={{ color: 'gray.300' }}>
              {item.description}
            </Text>
          ) : null}
          {statusState && (
            <Badge colorScheme={statusColor} width="fit-content">
              {statusLabel}
            </Badge>
          )}
          {progressValue !== null && (
            <Progress
              value={progressValue}
              size="sm"
              colorScheme="purple"
              borderRadius="full"
              data-testid="download-progress"
            />
          )}
          {statusMessage && (
            <Text fontSize="sm" color={isFailed ? 'red.500' : 'gray.600'}>
              {statusMessage}
            </Text>
          )}
        </Stack>
      </CardBody>
      {downloadedAtLabel && (
        <CardFooter pt={0}>
          <Text fontSize="xs" color="gray.500">
            Downloaded {downloadedAtLabel}
          </Text>
        </CardFooter>
      )}
    </Card>
  );
}
