// services/moon/src/components/SetupListItem.vue
<script lang="ts" setup>
import { computed } from 'vue';

type ServiceCategory = 'core' | 'addon' | string;

interface ServiceOption {
  name: string;
  category?: ServiceCategory;
  image?: string | null;
  description?: string | null;
  hostServiceUrl?: string | null;
  port?: number | null;
  health?: string | null;
  required?: boolean;
}

const props = defineProps<{
  service: ServiceOption;
  selected?: boolean;
  disabled?: boolean;
  installed?: boolean;
}>();

const emit = defineEmits<{
  (event: 'toggle', name: string): void;
}>();

const categoryLabel = computed(() => {
  const category = props.service.category ?? 'service';

  if (category === 'core') return 'Core Service';
  if (category === 'addon') return 'Addon';

  return category
    .replace(/[-_]/g, ' ')
    .replace(/\b\w/g, (char) => char.toUpperCase());
});

const isLocked = computed(() => props.service.required === true);
const isInstalled = computed(() => props.installed === true);
const isDisabled = computed(() => props.disabled || isLocked.value || isInstalled.value);

const handleToggle = () => {
  if (isDisabled.value) return;
  emit('toggle', props.service.name);
};

const descriptionText = computed(() => {
  if (props.service.description) {
    return props.service.description;
  }

  if (props.service.category === 'core') {
    return 'Essential Noona component.';
  }

  if (props.service.category === 'addon') {
    return 'Optional add-on service.';
  }

  return 'Service configuration';
});
</script>

<template>
  <v-list-item
    class="setup-list-item"
    :class="{
      'setup-list-item--selected': selected,
      'setup-list-item--disabled': disabled,
      'setup-list-item--locked': isLocked,
      'setup-list-item--installed': isInstalled,
    }"
    role="checkbox"
    :aria-checked="selected"
    :aria-disabled="isDisabled"
    :aria-required="isLocked"
    :tabindex="isDisabled ? -1 : 0"
    :ripple="!isDisabled"
    @click="handleToggle"
    @keydown.enter.prevent="handleToggle"
    @keydown.space.prevent="handleToggle"
  >
    <template #prepend>
      <v-checkbox-btn
        :model-value="selected"
        :disabled="isDisabled"
        color="primary"
        class="setup-list-item__checkbox"
        @click.stop="handleToggle"
        @keydown.enter.stop.prevent="handleToggle"
        @keydown.space.stop.prevent="handleToggle"
      />
    </template>

    <div class="setup-list-item__body">
      <div class="setup-list-item__header">
        <span class="setup-list-item__name">{{ service.name }}</span>
        <v-chip
          color="primary"
          size="x-small"
          variant="tonal"
          class="setup-list-item__chip text-uppercase font-weight-bold"
        >
          {{ categoryLabel }}
        </v-chip>
        <v-chip
          v-if="isInstalled"
          color="success"
          size="x-small"
          variant="tonal"
          class="setup-list-item__chip setup-list-item__chip--installed text-uppercase font-weight-bold"
        >
          <v-icon icon="mdi-check-circle-outline" size="small" class="mr-1" />
          Installed
        </v-chip>
        <v-chip
          v-if="isLocked"
          color="error"
          size="x-small"
          variant="tonal"
          class="setup-list-item__chip setup-list-item__chip--required text-uppercase font-weight-bold"
        >
          <v-icon icon="mdi-lock" size="small" class="mr-1" />
          Required
        </v-chip>
      </div>

      <p class="setup-list-item__description text-body-2">
        {{ descriptionText }}
      </p>

      <div class="setup-list-item__meta text-body-2 text-medium-emphasis">
        <div>
          <span class="font-weight-medium">Image:</span>
          <span class="ml-1">{{ service.image ?? 'Unknown' }}</span>
        </div>
        <div v-if="service.hostServiceUrl">
          <span class="font-weight-medium">Host URL:</span>
          <a
            :href="service.hostServiceUrl"
            target="_blank"
            rel="noopener"
            class="setup-list-item__link ml-1"
            @click.stop
          >
            {{ service.hostServiceUrl }}
          </a>
        </div>
        <div v-else-if="service.port != null">
          <span class="font-weight-medium">Port:</span>
          <span class="ml-1">{{ service.port }}</span>
        </div>
        <div v-if="service.health">
          <span class="font-weight-medium">Health:</span>
          <span class="ml-1">{{ service.health }}</span>
        </div>
      </div>
    </div>
  </v-list-item>
</template>

<style scoped>
.setup-list-item {
  border-radius: 8px;
  transition: background-color 0.2s ease, box-shadow 0.2s ease, transform 0.2s ease;
  cursor: pointer;
  padding-inline-end: 16px;
}

.setup-list-item:hover:not(.setup-list-item--disabled) {
  background-color: rgba(var(--v-theme-primary), 0.08);
}

.setup-list-item:focus-visible {
  outline: 2px solid rgba(var(--v-theme-primary), 0.6);
  outline-offset: 2px;
}

.setup-list-item--selected {
  box-shadow: inset 0 0 0 2px rgba(var(--v-theme-primary), 0.35);
  background-color: rgba(var(--v-theme-primary), 0.04);
}

.setup-list-item--disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.setup-list-item--locked {
  cursor: not-allowed;
}

.setup-list-item--installed {
  cursor: not-allowed;
}

.setup-list-item__checkbox {
  margin-inline-end: 12px;
}

.setup-list-item__body {
  width: 100%;
}

.setup-list-item__header {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 4px;
}

.setup-list-item__name {
  font-weight: 600;
  font-size: 1.05rem;
}

.setup-list-item__chip {
  letter-spacing: 0.08em;
}

.setup-list-item__chip--required {
  display: inline-flex;
  align-items: center;
  gap: 4px;
}

.setup-list-item__chip--installed {
  display: inline-flex;
  align-items: center;
  gap: 4px;
}

.setup-list-item__description {
  margin: 0 0 6px;
  color: rgba(var(--v-theme-on-surface), 0.74);
}

.setup-list-item__meta {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
}

.setup-list-item__link {
  text-decoration: none;
}

.setup-list-item__link:hover,
.setup-list-item__link:focus {
  text-decoration: underline;
}
</style>

// services/moon/src/components/SetupListItem.jsx
import React, { useMemo } from 'react';
import {
  Badge,
  Box,
  Checkbox,
  HStack,
  Icon,
  Link,
  Stack,
  Tag,
  Text,
  VStack,
} from '@chakra-ui/react';
import { getIconPath } from './icons.js';

function normalizeCategoryLabel(category) {
  if (!category) {
    return 'Service';
  }
  if (category === 'core') {
    return 'Core Service';
  }
  if (category === 'addon') {
    return 'Addon';
  }
  return category
    .toString()
    .replace(/[-_]/g, ' ')
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

function categoryDescription(service) {
  if (service?.description) {
    return service.description;
  }
  if (service?.category === 'core') {
    return 'Essential Noona component.';
  }
  if (service?.category === 'addon') {
    return 'Optional add-on service.';
  }
  return 'Service configuration';
}

function MdiIcon({ name }) {
  const path = getIconPath(name);
  return (
    <Icon viewBox="0 0 24 24" boxSize="1rem">
      <path fill="currentColor" d={path} />
    </Icon>
  );
}

export default function SetupListItem({
  service,
  selected = false,
  disabled = false,
  installed = false,
  onToggle,
}) {
  const isLocked = service?.required === true;
  const isInstalled = installed === true;
  const isDisabled = disabled || isLocked || isInstalled;

  const categoryLabel = useMemo(
    () => normalizeCategoryLabel(service?.category ?? 'service'),
    [service?.category],
  );

  const descriptionText = useMemo(() => categoryDescription(service), [service]);

  const handleToggle = () => {
    if (isDisabled) {
      return;
    }
    onToggle?.(service?.name ?? '');
  };

  const handleKeyDown = (event) => {
    if (isDisabled) {
      return;
    }
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      handleToggle();
    }
  };

  return (
    <Box
      role="checkbox"
      aria-checked={selected}
      aria-disabled={isDisabled}
      aria-required={isLocked}
      aria-label={service?.name ?? 'Service option'}
      tabIndex={isDisabled ? -1 : 0}
      borderWidth="1px"
      borderRadius="lg"
      p={4}
      bg={selected ? 'purple.50' : 'white'}
      _dark={{ bg: selected ? 'purple.900' : 'gray.800', borderColor: 'whiteAlpha.300' }}
      cursor={isDisabled ? 'not-allowed' : 'pointer'}
      opacity={isDisabled && !isLocked ? 0.75 : 1}
      onClick={handleToggle}
      onKeyDown={handleKeyDown}
      transition="box-shadow 0.2s ease, transform 0.2s ease"
      _hover={{
        boxShadow: isDisabled ? undefined : 'lg',
      }}
      data-testid={`setup-item-${service?.name ?? 'unknown'}`}
    >
      <HStack align="flex-start" spacing={4} mb={3}>
        <Checkbox
          isChecked={selected}
          isDisabled={isDisabled}
          onChange={(event) => {
            event.stopPropagation();
            handleToggle();
          }}
          onClick={(event) => event.stopPropagation()}
          size="lg"
          aria-label={service?.name ?? 'Service option'}
        />
        <VStack align="flex-start" spacing={2} flex="1">
          <HStack spacing={2} align="center" flexWrap="wrap">
            <Text fontWeight="semibold" fontSize="lg">
              {service?.name ?? 'Unknown service'}
            </Text>
            <Tag size="sm" colorScheme="purple" textTransform="uppercase">
              {categoryLabel}
            </Tag>
            {isInstalled && (
              <Tag size="sm" colorScheme="green" textTransform="uppercase">
                <HStack spacing={1}>
                  <MdiIcon name="mdi-check-circle-outline" />
                  <Text>Installed</Text>
                </HStack>
              </Tag>
            )}
            {isLocked && (
              <Tag size="sm" colorScheme="red" textTransform="uppercase">
                Required
              </Tag>
            )}
          </HStack>
          <Text fontSize="sm" color="gray.600" _dark={{ color: 'gray.300' }}>
            {descriptionText}
          </Text>
        </VStack>
      </HStack>

      <Stack spacing={1} fontSize="sm" color="gray.600" _dark={{ color: 'gray.300' }}>
        <HStack>
          <Text fontWeight="medium">Image:</Text>
          <Text>{service?.image ?? 'Unknown'}</Text>
        </HStack>
        {service?.hostServiceUrl ? (
          <HStack>
            <Text fontWeight="medium">Host URL:</Text>
            <Link href={service.hostServiceUrl} isExternal color="purple.500">
              {service.hostServiceUrl}
            </Link>
          </HStack>
        ) : service?.port != null ? (
          <HStack>
            <Text fontWeight="medium">Port:</Text>
            <Text>{service.port}</Text>
          </HStack>
        ) : null}
        {service?.health && (
          <HStack>
            <Text fontWeight="medium">Health:</Text>
            <Text>{service.health}</Text>
          </HStack>
        )}
        {service?.status && (
          <HStack>
            <Text fontWeight="medium">Status:</Text>
            <Badge colorScheme={isInstalled ? 'green' : 'gray'}>{service.status}</Badge>
          </HStack>
        )}
      </Stack>
    </Box>
  );
}
