// services/moon/src/pages/Home.vue
<script setup>
import {computed, onMounted} from 'vue';
import Header from '../components/Header.vue';
import {getRequiredServiceForPath, useServiceInstallationStore} from '../utils/serviceInstallationStore.js';

const servicePages = [
  {
    title: 'Warden',
    summary:
      'Orchestrator for the entire stack. Builds Docker images, provisions containers, enforces boot order, performs health checks, and manages rolling updates across master and node deployments.',
    path: '/warden',
    icon: 'mdi-shield-crown',
  },
  {
    title: 'Vault',
    summary:
      'Authentication and data access gateway. Issues JWTs to services, brokers reads/writes to MongoDB and Redis, and secures internal APIs.',
    path: '/vault',
    icon: 'mdi-safe-square',
  },
  {
    title: 'Portal',
    summary:
      "External integrations hub. Handles Discord command logic, listens for guild events, and bridges to Kavita's APIs.",
    path: '/portal',
    icon: 'mdi-transit-connection-variant',
  },
  {
    title: 'Sage',
    summary:
      'Monitoring and logging backbone using Prometheus for metrics collection and Grafana for visualization.',
    path: '/sage',
    icon: 'mdi-chart-box-outline',
  },
  {
    title: 'Moon Service',
    summary:
      'Web-based control center built with React. Provides dashboards for admins and readers, Discord authentication, AI chat, request management, and service status.',
    path: '/moon-service',
    icon: 'mdi-moon-waning-crescent',
  },
  {
    title: 'Raven',
    summary:
      'Custom Java-based scraper/downloader. Automates content acquisition, metadata enrichment, and CBZ packaging.',
    path: '/raven',
    icon: 'mdi-crow',
  },
  {
    title: 'Oracle',
    summary:
      'AI assistant layer powered by LangChain, LocalAI/AnythingLLM for conversational insights and recommendations.',
    path: '/oracle',
    icon: 'mdi-crystal-ball',
  },
];

const store = useServiceInstallationStore();

onMounted(() => {
  store.ensureLoaded();
});

const showSetupButton = computed(() => store.hasPendingSetup.value);

const serviceCards = computed(() =>
  servicePages.map((service) => {
    const requiredService = getRequiredServiceForPath(service.path);
    const installed = store.isServiceInstalled(requiredService);
    const loading = store.loading.value;
    const disabled = loading || (!!requiredService && !installed);
    let tooltip = '';

    if (loading) {
      tooltip = 'Checking installation status…';
    } else if (disabled) {
      tooltip = 'Service installation is still pending.';
    }

    return {
      ...service,
      requiredService,
      installed,
      disabled,
      tooltip,
    };
  }),
);
</script>

<template>
  <Header>
    <v-container class="py-12">
      <v-row justify="center" class="mb-12">
        <v-col cols="12" md="8" lg="6">
          <v-card class="pa-10 text-center" elevation="12">
            <v-img class="mx-auto mb-6" max-width="100" src="/logo.svg"/>
            <v-card-title class="text-h4 mb-2">Welcome to Noona</v-card-title>
            <v-card-subtitle class="mb-6">
              Explore the control surfaces for every service or jump straight into the setup wizard.
            </v-card-subtitle>
            <v-btn
                v-if="showSetupButton"
                color="primary"
                size="large"
                data-test="launch-setup"
                @click="$router.push('/setup')"
            >
              Launch Setup Wizard
            </v-btn>
          </v-card>
        </v-col>
      </v-row>

      <v-row class="service-grid" dense>
        <v-col
            v-for="card in serviceCards"
            :key="card.path"
            cols="12"
            md="6"
            lg="4"
        >
          <v-card class="h-100 d-flex flex-column justify-space-between" elevation="4">
            <div class="pa-6">
              <v-icon :icon="card.icon" size="40" class="mb-4 text-primary"/>
              <h2 class="text-h5 mb-3">{{ card.title }}</h2>
              <p class="text-body-2 mb-6">{{ card.summary }}</p>
            </div>
            <v-divider/>
            <v-card-actions>
              <v-btn
                  block
                  color="secondary"
                  variant="text"
                  :disabled="card.disabled"
                  :title="card.disabled ? card.tooltip : undefined"
                  :data-test="`service-link-${card.path}`"
                  @click="card.disabled ? null : $router.push(card.path)"
              >
                View {{ card.title }}
              </v-btn>
            </v-card-actions>
          </v-card>
        </v-col>
      </v-row>
    </v-container>
  </Header>
</template>

// services/moon/src/pages/Home.jsx
import React, { useEffect, useMemo } from 'react';
import { Button } from '@textkernel/oneui';
import { useNavigate } from 'react-router-dom';
import { getIconPath } from '../components/icons.js';
import {
  getRequiredServiceForPath,
  useServiceInstallation,
} from '../state/serviceInstallationContext.tsx';

const SERVICE_PAGES = [
  {
    title: 'Warden',
    summary:
      'Orchestrator for the entire stack. Builds Docker images, provisions containers, enforces boot order, performs health checks, and manages rolling updates across master and node deployments.',
    path: '/warden',
    icon: 'mdi-shield-crown',
  },
  {
    title: 'Vault',
    summary:
      'Authentication and data access gateway. Issues JWTs to services, brokers reads/writes to MongoDB and Redis, and secures internal APIs.',
    path: '/vault',
    icon: 'mdi-safe-square',
  },
  {
    title: 'Portal',
    summary:
      "External integrations hub. Handles Discord command logic, listens for guild events, and bridges to Kavita's APIs.",
    path: '/portal',
    icon: 'mdi-transit-connection-variant',
  },
  {
    title: 'Sage',
    summary:
      'Monitoring and logging backbone using Prometheus for metrics collection and Grafana for visualization.',
    path: '/sage',
    icon: 'mdi-chart-box-outline',
  },
  {
    title: 'Moon Service',
    summary:
      'Web-based control center built with React. Provides dashboards for admins and readers, Discord authentication, AI chat, request management, and service status.',
    path: '/moon-service',
    icon: 'mdi-moon-waning-crescent',
  },
  {
    title: 'Raven',
    summary:
      'Custom Java-based scraper/downloader. Automates content acquisition, metadata enrichment, and CBZ packaging.',
    path: '/raven',
    icon: 'mdi-crow',
  },
  {
    title: 'Oracle',
    summary:
      'AI assistant layer powered by LangChain, LocalAI/AnythingLLM for conversational insights and recommendations.',
    path: '/oracle',
    icon: 'mdi-crystal-ball',
  },
];

export default function HomePage() {
  const navigate = useNavigate();
  const { ensureLoaded, hasPendingSetup, isServiceInstalled, loading } = useServiceInstallation();

  useEffect(() => {
    ensureLoaded().catch(() => {});
  }, [ensureLoaded]);

  const serviceCards = useMemo(() => {
    return SERVICE_PAGES.map((service) => {
      const requiredService = getRequiredServiceForPath(service.path);
      const installed = isServiceInstalled(requiredService);
      const disabled = loading || (!!requiredService && !installed);
      let tooltip = '';

      if (loading) {
        tooltip = 'Checking installation status…';
      } else if (disabled) {
        tooltip = 'Service installation is still pending.';
      }

      return {
        ...service,
        requiredService,
        installed,
        disabled,
        tooltip,
      };
    });
  }, [isServiceInstalled, loading]);

  return (
    <div className="stack home-page">
      <section className="home-hero">
        <img src="/logo.svg" alt="Noona" className="home-hero__logo" />
        <h1>Welcome to Noona</h1>
        <p>Explore the control surfaces for every service or jump straight into the setup wizard.</p>
        {hasPendingSetup && (
          <Button context="primary" size="large" data-testid="launch-setup" onClick={() => navigate('/setup')}>
            Launch Setup Wizard
          </Button>
        )}
      </section>

      <div className="home-cards">
        {serviceCards.map((card) => (
          <article className="home-card" key={card.path}>
            <div className="home-card__header">
              <svg className="home-card__icon" viewBox="0 0 24 24" aria-hidden="true">
                <path fill="currentColor" d={getIconPath(card.icon)} />
              </svg>
              <h3>{card.title}</h3>
            </div>
            <p className="home-card__body">{card.summary}</p>
            <Button
              variant="outlined"
              context="primary"
              isBlock
              disabled={card.disabled}
              title={card.disabled ? card.tooltip : undefined}
              data-testid={`service-link-${card.path}`}
              onClick={() => !card.disabled && navigate(card.path)}
            >
              View {card.title}
            </Button>
          </article>
        ))}
      </div>
    </div>
  );
}
