// services/moon/src/pages/Raven.jsx
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  Button,
  Callout,
  Input,
  LoadingSpinner,
  Modal,
  StatusBadge,
  Text as OneUIText,
} from '@textkernel/oneui';
import { getIconPath } from '../components/icons.js';
import RavenLibraryGrid from '../components/raven/RavenLibraryGrid.jsx';
import {
  fetchDownloadStatuses,
  fetchLibrary,
  searchTitles,
  startDownload,
} from '../utils/ravenClient.js';
import useDisclosureState from '../utils/useDisclosureState.ts';

const POLL_INTERVAL = 5000;

function parseLibraryResponse(payload) {
  if (!payload) return [];
  if (Array.isArray(payload)) return payload;
  if (Array.isArray(payload.library)) return payload.library;
  if (Array.isArray(payload.series)) return payload.series;
  if (Array.isArray(payload.items)) return payload.items;
  return [];
}

function parseDownloadsResponse(payload) {
  if (!payload) return [];
  if (Array.isArray(payload)) return payload;
  if (Array.isArray(payload.downloads)) return payload.downloads;
  if (Array.isArray(payload.statuses)) return payload.statuses;
  return [];
}

function statusKey(status) {
  if (!status) return null;
  return (
    status.libraryId ??
    status.id ??
    status.searchId ??
    status.seriesId ??
    status.title ??
    null
  );
}

function SearchIcon() {
  return (
    <span className="raven-input-icon" aria-hidden="true">
      <svg viewBox="0 0 24 24">
        <path fill="currentColor" d={getIconPath('mdi-magnify')} />
      </svg>
    </span>
  );
}

export default function RavenPage() {
  const [library, setLibrary] = useState([]);
  const [libraryLoading, setLibraryLoading] = useState(false);
  const [libraryError, setLibraryError] = useState('');

  const [downloads, setDownloads] = useState([]);
  const [downloadsError, setDownloadsError] = useState('');

  const [searchQuery, setSearchQuery] = useState('');
  const [searchResults, setSearchResults] = useState([]);
  const [searchLoading, setSearchLoading] = useState(false);
  const [searchError, setSearchError] = useState('');

  const [downloadError, setDownloadError] = useState('');
  const [downloadLoading, setDownloadLoading] = useState(false);
  const [selectedOption, setSelectedOption] = useState(null);

  const completedDownloads = useRef(new Set());

  const { isOpen, onOpen, onClose } = useDisclosureState(false);

  const resetDialogState = useCallback(() => {
    setSearchQuery('');
    setSearchResults([]);
    setSearchError('');
    setDownloadError('');
    setDownloadLoading(false);
    setSelectedOption(null);
  }, []);

  const closeDialog = useCallback(() => {
    onClose();
    resetDialogState();
  }, [onClose, resetDialogState]);

  const loadLibrary = useCallback(async () => {
    setLibraryLoading(true);
    setLibraryError('');
    try {
      const payload = await fetchLibrary();
      setLibrary(parseLibraryResponse(payload));
    } catch (error) {
      setLibraryError(error instanceof Error ? error.message : 'Failed to load library.');
    } finally {
      setLibraryLoading(false);
    }
  }, []);

  const refreshDownloads = useCallback(async () => {
    try {
      setDownloadsError('');
      const payload = await fetchDownloadStatuses();
      const list = parseDownloadsResponse(payload);
      setDownloads(list);

      let shouldRefreshLibrary = false;
      list.forEach((status) => {
        const key = statusKey(status);
        if (status?.state === 'completed' && key && !completedDownloads.current.has(key)) {
          completedDownloads.current.add(key);
          shouldRefreshLibrary = true;
        }
      });

      if (shouldRefreshLibrary) {
        await loadLibrary();
      }
    } catch (error) {
      setDownloadsError(
        error instanceof Error ? error.message : 'Failed to load download status.',
      );
    }
  }, [loadLibrary]);

  useEffect(() => {
    loadLibrary().catch(() => {});
  }, [loadLibrary]);

  useEffect(() => {
    let isMounted = true;

    const poll = async () => {
      if (!isMounted) return;
      await refreshDownloads();
    };

    poll().catch(() => {});
    const handle = window.setInterval(() => {
      poll().catch(() => {});
    }, POLL_INTERVAL);

    return () => {
      isMounted = false;
      window.clearInterval(handle);
    };
  }, [refreshDownloads]);

  const performSearch = useCallback(
    async (event) => {
      event?.preventDefault?.();
      const query = searchQuery.trim();
      if (!query) {
        setSearchError('Enter a search term to query the Raven index.');
        setSearchResults([]);
        return;
      }

      setSearchLoading(true);
      setSearchError('');
      setDownloadError('');
      setSelectedOption(null);

      try {
        const payload = await searchTitles(query);
        const results = Array.isArray(payload?.results)
          ? payload.results
          : Array.isArray(payload)
          ? payload
          : [];
        setSearchResults(results);
        if (!results.length) {
          setSearchError('No results were found for that query.');
        }
      } catch (error) {
        setSearchError(error instanceof Error ? error.message : 'Search failed.');
        setSearchResults([]);
      } finally {
        setSearchLoading(false);
      }
    },
    [searchQuery],
  );

  const selectOption = useCallback((searchId, optionIndex) => {
    setSelectedOption({ searchId, optionIndex });
  }, []);

  const isSelected = useCallback(
    (searchId, optionIndex) =>
      selectedOption?.searchId === searchId && selectedOption?.optionIndex === optionIndex,
    [selectedOption],
  );

  const activeSelectionLabel = useMemo(() => {
    if (!selectedOption) {
      return '';
    }
    const match = searchResults.find((result) => {
      const id = result?.id ?? result?.searchId;
      return id === selectedOption.searchId;
    });
    if (!match) {
      return '';
    }
    const option = match.options?.[selectedOption.optionIndex];
    const baseTitle = match.title ?? match.name ?? 'Selected option';
    const optionLabel = option?.label ?? option?.name ?? `Option ${selectedOption.optionIndex + 1}`;
    return `${baseTitle} — ${optionLabel}`;
  }, [searchResults, selectedOption]);

  const startDownloadFlow = useCallback(async () => {
    if (!selectedOption) {
      setDownloadError('Select an option before confirming the download.');
      return;
    }
    setDownloadLoading(true);
    setDownloadError('');

    try {
      await startDownload(selectedOption);
      await refreshDownloads();
      await loadLibrary();
      closeDialog();
    } catch (error) {
      setDownloadError(error instanceof Error ? error.message : 'Failed to start download.');
    } finally {
      setDownloadLoading(false);
    }
  }, [closeDialog, loadLibrary, refreshDownloads, selectedOption]);

  const openDialog = useCallback(() => {
    resetDialogState();
    onOpen();
  }, [onOpen, resetDialogState]);

  const activeDownloads = useMemo(() => downloads ?? [], [downloads]);

  return (
    <div className="stack raven-page" data-testid="raven-page">
      <div className="raven-page__header">
        <h1>Raven Library</h1>
        <Button context="primary" onClick={openDialog} data-testid="open-add-dialog">
          Add new title
        </Button>
      </div>

      {downloadsError && (
        <Callout context="critical">
          <OneUIText isBold>{downloadsError}</OneUIText>
        </Callout>
      )}

      <section className="stack raven-section">
        <h2>Library</h2>
        {libraryLoading ? (
          <div className="raven-loading">
            <LoadingSpinner />
          </div>
        ) : libraryError ? (
          <Callout context="critical">
            <OneUIText>{libraryError}</OneUIText>
          </Callout>
        ) : library.length === 0 ? (
          <div className="raven-empty" data-testid="library-empty">
            <svg viewBox="0 0 24 24" aria-hidden="true">
              <path fill="currentColor" d={getIconPath('mdi-crow')} />
            </svg>
            <p className="raven-empty__title">Your Raven library is empty.</p>
            <p>Start a search to download your first telemetry series.</p>
          </div>
        ) : (
          <RavenLibraryGrid items={library} statuses={activeDownloads} />
        )}
      </section>

      {activeDownloads.length > 0 && (
        <section className="stack raven-section">
          <h2>Active downloads</h2>
          <div className="stack">
            {activeDownloads.map((status) => {
              const key = statusKey(status) ?? Math.random().toString(36);
              return (
                <div className="raven-download" key={key}>
                  <p className="raven-download__title">{status.title ?? 'Processing download'}</p>
                  <OneUIText size="small" context="neutral">
                    {status.message ?? 'Preparing files…'}
                  </OneUIText>
                  {typeof status.progress === 'number' && (
                    <StatusBadge context="info" variant="subtle">
                      {Math.round(status.progress)}%
                    </StatusBadge>
                  )}
                </div>
              );
            })}
          </div>
        </section>
      )}

      <Modal
        isOpen={isOpen}
        onRequestClose={closeDialog}
        contentLabel="Add a new title"
        className="raven-modal"
        overlayClassName="app-modal__overlay"
      >
        <div className="stack" data-testid="add-dialog">
          <div className="raven-modal__header">
            <h2>Add a new title</h2>
            <Button variant="ghost" context="secondary" onClick={closeDialog}>
              Close
            </Button>
          </div>
          <form className="stack" onSubmit={performSearch}>
            <label htmlFor="raven-search-query" className="form-label">
              Search the Raven index
            </label>
            <Input
              id="raven-search-query"
              value={searchQuery}
              onChange={(event) => setSearchQuery(event.target.value)}
              placeholder="Enter a series name or keyword"
              data-testid="search-query"
              leadingIcon={<SearchIcon />}
            />
            <Button
              type="submit"
              context="primary"
              isLoading={searchLoading}
              data-testid="submit-search"
            >
              Search
            </Button>
          </form>

          {searchLoading && (
            <div className="raven-loading">
              <LoadingSpinner />
            </div>
          )}

          {searchError && !searchLoading && (
            <Callout context="critical" data-testid="search-error">
              <OneUIText>{searchError}</OneUIText>
            </Callout>
          )}

          {searchResults.length > 0 && (
            <div className="stack" data-testid="search-results">
              {searchResults.map((result) => {
                const resultId = result.id ?? result.searchId;
                return (
                  <div className="raven-result" key={resultId ?? Math.random().toString(36)}>
                    <p className="raven-result__title">{result.title ?? result.name}</p>
                    {result.description && (
                      <OneUIText size="small" context="neutral">
                        {result.description}
                      </OneUIText>
                    )}
                    <div className="stack stack--row stack--wrap raven-option-list">
                      {(result.options ?? []).map((option, optionIndex) => (
                        <Button
                          key={optionIndex}
                          variant={isSelected(resultId, optionIndex) ? 'filled' : 'outlined'}
                          context={isSelected(resultId, optionIndex) ? 'primary' : 'secondary'}
                          onClick={() => selectOption(resultId, optionIndex)}
                          data-testid="search-option"
                        >
                          {option?.label ?? option?.name ?? `Option ${optionIndex + 1}`}
                        </Button>
                      ))}
                    </div>
                  </div>
                );
              })}
            </div>
          )}

          {downloadError && (
            <Callout context="critical" data-testid="download-error">
              <OneUIText>{downloadError}</OneUIText>
            </Callout>
          )}

          {activeSelectionLabel && (
            <Callout context="info" data-testid="selected-option">
              <OneUIText>{activeSelectionLabel}</OneUIText>
            </Callout>
          )}

          <div className="raven-modal__footer">
            <Button variant="ghost" context="secondary" onClick={closeDialog}>
              Cancel
            </Button>
            <Button
              context="primary"
              onClick={startDownloadFlow}
              disabled={!selectedOption}
              isLoading={downloadLoading}
              data-testid="confirm-download"
            >
              Confirm download
            </Button>
          </div>
        </div>
      </Modal>
    </div>
  );
}

// services/moon/src/pages/Raven.vue
<script setup>
import {computed, onBeforeUnmount, onMounted, ref} from 'vue';
import Header from '../components/Header.vue';
import RavenLibraryGrid from '../components/raven/RavenLibraryGrid.vue';
import {
  fetchDownloadStatuses,
  fetchLibrary,
  searchTitles,
  startDownload,
} from '../utils/ravenClient.js';

const library = ref([]);
const libraryLoading = ref(false);
const libraryError = ref('');

const downloads = ref([]);
const downloadsError = ref('');

const isDialogOpen = ref(false);
const searchQuery = ref('');
const searchResults = ref([]);
const searchLoading = ref(false);
const searchError = ref('');
const downloadError = ref('');
const downloadLoading = ref(false);
const selectedOption = ref(null);

const POLL_INTERVAL = 5000;
let pollHandle = null;

const completedDownloads = new Set();

const resetDialogState = () => {
  searchQuery.value = '';
  searchResults.value = [];
  searchError.value = '';
  downloadError.value = '';
  selectedOption.value = null;
  downloadLoading.value = false;
};

const openAddDialog = () => {
  resetDialogState();
  isDialogOpen.value = true;
};

const closeAddDialog = () => {
  isDialogOpen.value = false;
  resetDialogState();
};

const parseLibraryResponse = (payload) => {
  if (!payload) return [];
  if (Array.isArray(payload)) return payload;
  if (Array.isArray(payload.library)) return payload.library;
  if (Array.isArray(payload.series)) return payload.series;
  if (Array.isArray(payload.items)) return payload.items;
  return [];
};

const parseDownloadsResponse = (payload) => {
  if (!payload) return [];
  if (Array.isArray(payload)) return payload;
  if (Array.isArray(payload.downloads)) return payload.downloads;
  if (Array.isArray(payload.statuses)) return payload.statuses;
  return [];
};

const statusKey = (status) => {
  if (!status) return null;
  return (
    status.libraryId ??
    status.id ??
    status.searchId ??
    status.seriesId ??
    status.title ??
    null
  );
};

const loadLibrary = async () => {
  libraryLoading.value = true;
  libraryError.value = '';
  try {
    const payload = await fetchLibrary();
    library.value = parseLibraryResponse(payload);
  } catch (error) {
    libraryError.value = error instanceof Error ? error.message : 'Failed to load library.';
  } finally {
    libraryLoading.value = false;
  }
};

const refreshDownloads = async () => {
  try {
    downloadsError.value = '';
    const payload = await fetchDownloadStatuses();
    const list = parseDownloadsResponse(payload);
    downloads.value = list;

    let shouldRefreshLibrary = false;
    list.forEach((status) => {
      const key = statusKey(status);
      if (status?.state === 'completed' && key && !completedDownloads.has(key)) {
        completedDownloads.add(key);
        shouldRefreshLibrary = true;
      }
    });

    if (shouldRefreshLibrary) {
      await loadLibrary();
    }
  } catch (error) {
    downloadsError.value =
      error instanceof Error ? error.message : 'Failed to load download status.';
  }
};

const activeDownloads = computed(() => downloads.value ?? []);

const performSearch = async () => {
  const query = searchQuery.value.trim();
  if (!query) {
    searchError.value = 'Please enter a search term.';
    return;
  }

  searchLoading.value = true;
  searchError.value = '';
  downloadError.value = '';
  searchResults.value = [];
  selectedOption.value = null;

  try {
    const payload = await searchTitles(query);
    const results = payload?.results ?? payload?.options ?? payload;
    searchResults.value = Array.isArray(results) ? results : [];
    if (!searchResults.value.length) {
      searchError.value = 'No matches found.';
    }
  } catch (error) {
    searchError.value = error instanceof Error ? error.message : 'Failed to search titles.';
    searchResults.value = [];
  } finally {
    searchLoading.value = false;
  }
};

const selectOption = (searchId, optionIndex) => {
  selectedOption.value = {searchId, optionIndex};
  downloadError.value = '';
};

const isSelected = (result, optionIndex) => {
  const id = result?.id ?? result?.searchId;
  return (
    selectedOption.value?.searchId === id &&
    selectedOption.value?.optionIndex === optionIndex
  );
};

const canConfirmDownload = computed(
  () => Boolean(selectedOption.value) && !downloadLoading.value,
);

const startDownloadFlow = async () => {
  if (!selectedOption.value) return;

  downloadLoading.value = true;
  downloadError.value = '';

  try {
    await startDownload({
      searchId: selectedOption.value.searchId,
      optionIndex: selectedOption.value.optionIndex,
    });
    closeAddDialog();
    await refreshDownloads();
  } catch (error) {
    downloadError.value =
      error instanceof Error ? error.message : 'Failed to start download.';
  } finally {
    downloadLoading.value = false;
  }
};

const activeSearchSelectionLabel = computed(() => {
  if (!selectedOption.value) return '';
  const {searchId, optionIndex} = selectedOption.value;
  const result = searchResults.value.find(
    (entry) => (entry?.id ?? entry?.searchId) === searchId,
  );
  if (!result) return '';
  const option = result.options?.[optionIndex];
  const optionLabel = option?.label ?? option?.name ?? `Option ${optionIndex + 1}`;
  const title = result.title ?? result.name ?? 'Selected title';
  return `${title} – ${optionLabel}`;
});

onMounted(() => {
  loadLibrary();
  refreshDownloads();
  pollHandle = setInterval(() => {
    refreshDownloads();
  }, POLL_INTERVAL);
});

onBeforeUnmount(() => {
  if (pollHandle) {
    clearInterval(pollHandle);
    pollHandle = null;
  }
});
</script>

<template>
  <Header>
    <v-container class="py-12">
      <v-row class="align-center mb-6">
        <v-col cols="12" md="8" class="d-flex justify-space-between flex-column flex-md-row">
          <div class="mb-4 mb-md-0">
            <h1 class="text-h4 font-weight-medium mb-1">Raven Library</h1>
            <p class="text-body-1 text-medium-emphasis mb-0">
              Monitor downloads and manage your telemetry series.
            </p>
          </div>
          <v-btn
              color="primary"
              prepend-icon="mdi-plus"
              class="align-self-md-end"
              data-test="open-add-dialog"
              @click="openAddDialog"
          >
            Add new title
          </v-btn>
        </v-col>
      </v-row>

      <v-row v-if="libraryError" class="mb-4">
        <v-col cols="12">
          <v-alert
              type="error"
              variant="tonal"
              data-test="library-error"
          >
            {{ libraryError }}
          </v-alert>
        </v-col>
      </v-row>

      <v-row v-if="downloadsError" class="mb-4">
        <v-col cols="12">
          <v-alert
              type="warning"
              variant="tonal"
              data-test="downloads-error"
          >
            {{ downloadsError }}
          </v-alert>
        </v-col>
      </v-row>

      <v-row v-if="libraryLoading" class="mb-6">
        <v-col cols="12">
          <v-progress-linear indeterminate color="primary" />
        </v-col>
      </v-row>

      <div
          v-if="!libraryLoading && !library.length"
          class="text-center py-16 text-medium-emphasis"
          data-test="library-empty"
      >
        <v-icon color="primary" size="64" class="mb-4">mdi-crow</v-icon>
        <div class="text-h5 mb-2">Your Raven library is empty.</div>
        <div class="text-body-1">
          Start a search to download your first telemetry series.
        </div>
      </div>

      <RavenLibraryGrid
          v-else
          :items="library"
          :statuses="activeDownloads"
      />
    </v-container>

    <v-dialog v-model="isDialogOpen" max-width="640">
      <v-card data-test="add-dialog">
        <v-card-title class="text-h5">Add a new title</v-card-title>
        <v-card-text>
          <v-form data-test="search-form" @submit.prevent="performSearch">
            <v-text-field
                v-model="searchQuery"
                label="Search the Raven index"
                prepend-inner-icon="mdi-magnify"
                clearable
                data-test="search-query"
            />
            <v-btn
                type="submit"
                color="primary"
                class="mt-2"
                block
                :loading="searchLoading"
                :disabled="searchLoading"
                data-test="submit-search"
            >
              Search
            </v-btn>
          </v-form>

          <v-progress-linear
              v-if="searchLoading"
              class="my-4"
              indeterminate
              color="primary"
          />

          <v-alert
              v-if="searchError"
              type="error"
              variant="tonal"
              class="mt-4"
              data-test="search-error"
          >
            {{ searchError }}
          </v-alert>

          <div v-if="searchResults.length" class="mt-4" data-test="search-results">
            <div
                v-for="result in searchResults"
                :key="result.id ?? result.searchId"
                class="mb-4"
                data-test="search-result"
            >
              <div class="text-subtitle-1 font-weight-medium">
                {{ result.title ?? result.name }}
              </div>
              <div v-if="result.description" class="text-body-2 text-medium-emphasis mb-2">
                {{ result.description }}
              </div>
              <div class="d-flex flex-wrap gap-2">
                <v-btn
                    v-for="(option, optionIndex) in result.options ?? []"
                    :key="optionIndex"
                    variant="outlined"
                    :color="isSelected(result, optionIndex) ? 'primary' : undefined"
                    data-test="search-option"
                    @click="selectOption(result.id ?? result.searchId, optionIndex)"
                >
                  {{ option?.label ?? option?.name ?? `Option ${optionIndex + 1}` }}
                </v-btn>
              </div>
            </div>
          </div>

          <v-alert
              v-if="downloadError"
              type="error"
              variant="tonal"
              data-test="download-error"
          >
            {{ downloadError }}
          </v-alert>

          <v-alert
              v-if="activeSearchSelectionLabel"
              type="info"
              variant="tonal"
              class="mt-4"
              data-test="selected-option"
          >
            {{ activeSearchSelectionLabel }}
          </v-alert>
        </v-card-text>
        <v-card-actions class="justify-end">
          <v-btn variant="text" @click="closeAddDialog">Cancel</v-btn>
          <v-btn
              color="primary"
              :disabled="!canConfirmDownload"
              :loading="downloadLoading"
              data-test="confirm-download"
              @click="startDownloadFlow"
          >
            Confirm download
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </Header>
</template>
